### ISSUE TITLE
marsjaninzmarsa → "problem z parsowaniem nicków zawierających myślnik"

### ISSUE THREAD

**Issue by MargatroidAlice** [TeMPOraL/alice#109]

**Comment by marsjaninzmarsa** [comment]
<marsjaninzmarsa> kto to kreska?
<Magda_M> marsjaninzmarsa: chyba nie wiem, o kogo Ci chodzi...
<marsjaninzmarsa> zapamiętaj: kreska kreska-groteska
<Magda_M> Zapamiętałam kreska jako kreska.
<marsjaninzmarsa> zapamiętaj: kresc kreska-groteska
<Magda_M> Zapamiętałam kresc jako kreska.
<marsjaninzmarsa> kto to "kresce"?
<Magda_M> marsjaninzmarsa: chyba nie wiem, o kogo Ci chodzi...
<marsjaninzmarsa> kto to kresce?
<Magda_M> marsjaninzmarsa: kreska
